### PR TITLE
bob nelkin extension layer

### PR DESCRIPTION
**Pull request by bnaismith**

### CODE REVIEW

**Comment by bnaismith** [comment]
Pull request to add Bob Nelkin collection extension layer and two new source data folders (updated OCR and POS-tagged texts)

**Comment by tyt3** [comment]
Thank you for your contribution, @bnaismith! I've begun reviewing your PR and made some changes (see [5957798](https://github.com/CaDatPitt/data-layers/pull/29/commits/59577980e63d9fcdfe78cb57f2b89e7cd0303531)). I will merge your branch to the main branch once you resolve the 3 data files in the `natural-language-processing_naismith` directory by either moving them to the folder(s) containing the Jupyter Notebook that produced them and/or explaining in the main README file how they fit into the extension layer outputs. Feel free to make any other changes as you see fit.

**Review by tyt3 — CHANGES_REQUESTED** [review]
Thank you for your contribution, @bnaismith! I've begun reviewing your PR and made some changes (see commits [5957798](https://github.com/CaDatPitt/data-layers/commit/59577980e63d9fcdfe78cb57f2b89e7cd0303531) and [c78ac4e](https://github.com/CaDatPitt/data-layers/commit/c78ac4e94d2cfd075d2456c8ada39fe25fd47b6b)). I will merge your branch to the main branch once you resolve the following:

- the 3 data files in the natural-language-processing_naismith directory should be moved to the folder(s) containing the Jupyter Notebook that produced them and/or explained in the main README file (e.g., how they fit into the extension layer outputs). 
- the `CLAWS-tagged_naismith` and `ocr_naismith` folders (moved from `source-data` to `extension-layers`) need README files.
 
Feel free to make any other changes as you see fit.

**Comment by bnaismith** [comment]
Requested changes made to readme files and organization

**Review by tyt3 — APPROVED** [review]

**Pull request merged**
